version: "3.7"

services:
  firefox_java6_x11vnc:
    build:
      context: "."
      dockerfile: "./Dockerfile.firefox_java6_x11vnc"
      cache_from:
        - "lipcomputing/novnc_openbox"
    environment:
      SERVERNUM: 10
      VNC_PASSWD: "password"
      VNC_PORT: 5910

  dl160_g5g6_java6_x11vnc:
    build:
      context: "."
      dockerfile: "./Dockerfile.dl160_g5g6_java6_x11vnc"
      cache_from:
        - "lipcomputing/novnc_openbox"
    environment:
      SERVERNUM: 11
      VNC_PASSWD: "password"
      VNC_PORT: 5911

  novnc_firefox_java6:
    build:
      context: "."
      dockerfile: "./Dockerfile.novnc_openbox"
    environment:
      VNC_PORT: 5910
      noVNC_PORT: 6080

  novnc_dl160_g5g6_java6:
    build:
      context: "."
      dockerfile: "./Dockerfile.novnc_openbox"
    environment:
      VNC_PORT: 5911
      noVNC_PORT: 6081

