version: "3.7"

services:
  firefox_java6_x11vnc:
    environment:
      SERVERNUM: 1
      VNC_PASSWD: "password"

  dl160_g5g6_java6_x11vnc:
    environment:
      SERVERNUM: 2
      VNC_PASSWD: "password"

  novnc_firefox_java6:
    environment:
      VNC_PORT: 5902
      noVNC_PORT: 6080

  novnc_dl160_g5g6_java6:
    environment:
      VNC_PORT: 5903
      noVNC_PORT: 6081

