version: "3.7"

services:
  firefox_java6_x11vnc:
    image: "lipcomputing/firefox-x11vnc-java6:latest"
    container_name: "firefox_java6_x11vnc"
    network_mode: "host"
    depends_on:
      - novnc_openbox

  novnc_openbox:
    image: "lipcomputing/novnc_openbox:latest"
    container_name: "novnc_openbox"
    network_mode: "host"

