version: "3.7"

services:
  firefox_java6_x11vnc:
    environment:
      SERVERNUM: 10
      VNC_PASSWD: "password"
      VNC_PORT: 5910

  dl160_g5g6_java6_x11vnc:
    environment:
      SERVERNUM: 11
      VNC_PASSWD: "password"
      VNC_PORT: 5911

  novnc_firefox_java6:
    environment:
      VNC_PORT: 5910
      noVNC_PORT: 6080

  novnc_dl160_g5g6_java6:
    environment:
      VNC_PORT: 5911
      noVNC_PORT: 6081

